version: '3.8'

services:
  api:
    build: .
    container_name: system_barbershop
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/barbershop
    volumes:
      - .:/app
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: system_barbershop_postgres
    restart: always
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: